### ISSUE TITLE
Install fails on node 7.x (OSX Sierra)

### ISSUE THREAD

**Issue by timkelty** [pswai/git-sweep#10]
Works fine on 6.2.2.

```not ok
Failed to execute '/Users/timkelty/.nvm/versions/node/v7.4.0/bin/node /Users/timkelty/.nvm/versions/node/v7.4.0/lib/node_modules/git-sweep/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/timkelty/.nvm/versions/node/v7.4.0/lib/node_modules/git-sweep/node_modules/nodegit/build/Release/nodegit.node --module_name=nodegit --module_path=/Users/timkelty/.nvm/versions/node/v7.4.0/lib/node_modules/git-sweep/node_modules/nodegit/build/Release' (1)
[nodegit] ERROR - Could not finish install
[nodegit] ERROR - finished with error code: 1
/Users/timkelty/.nvm/versions/node/v7.4.0/lib
└── (empty)```

Here is my complete log: https://gist.github.com/7e39f6d1f8c2cf84990be73aa671070b

**Comment by pswai** [comment]
@timkelty Thanks for reporting. :)

This is interesting. I tried on El Capitan this afternoon, it worked fine. Now I am trying on Sierra and it does not work.

Let me have a look tomorrow.

FYI, pre-compiled NodeGit for 7.4.0 is still not available on s3 yet. It is already on master so this should be not a problem once it's released

**Comment by pswai** [comment]
Emitted stderr:

```
$ npm i -g git-sweep
/Users/parksoon_my/.nvm/versions/node/v7.4.0/bin/git-sweep -> /Users/parksoon_my/.nvm/versions/node/v7.4.0/lib/node_modules/git-sweep/bin/git-sweep

> nodegit@0.16.0 install /Users/parksoon_my/.nvm/versions/node/v7.4.0/lib/node_modules/git-sweep/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /Users/parksoon_my/.nvm/versions/node/v7.4.0/lib/node_modules/git-sweep/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/parksoon_my/.nvm/versions/node/v7.4.0/lib/node_modules/git-sweep/node_modules/nodegit/vendor/openssl/openssl
/Users/parksoon_my/.nvm/versions/node/v7.4.0/lib/node_modules/git-sweep/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/parksoon_my/.nvm/versions/node/v7.4.0/lib/node_modules/git-sweep/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/parksoon_my/.nvm/versions/node/v7.4.0/lib/node_modules/git-sweep/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/parksoon_my/.nvm/versions/node/v7.4.0/lib/node_modules/git-sweep/node_modules/nodegit/vendor/openssl/openssl' }
/Users/parksoon_my/.nvm/versions/node/v7.4.0/lib/node_modules/git-sweep/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/parksoon_my/.nvm/versions/node/v7.4.0/lib/node_modules/git-sweep/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /Users/parksoon_my/.nvm/versions/node/v7.4.0/lib/node_modules/git-sweep/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/parksoon_my/.nvm/versions/node/v7.4.0/lib/node_modules/git-sweep/node_modules/nodegit/vendor/openssl/openssl
/Users/parksoon_my/.nvm/versions/node/v7.4.0/lib/node_modules/git-sweep/node_modules/nodegit/vendor/libssh2/missing: Unknown `--is-lightweight' option
Try `/Users/parksoon_my/.nvm/versions/node/v7.4.0/lib/node_modules/git-sweep/node_modules/nodegit/vendor/libssh2/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: No crypto library found!
Try --with-libssl-prefix=PATH
 or --with-libgcrypt-prefix=PATH
 or --with-wincng on Windows

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/Users/parksoon_my/.nvm/versions/node/v7.4.0/lib/node_modules/git-sweep/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/Users/parksoon_my/.nvm/versions/node/v7.4.0/lib/node_modules/git-sweep/node_modules/nodegit/vendor/openssl/openssl' }
/Users/parksoon_my/.nvm/versions/node/v7.4.0/lib
└── (empty)
```

**Comment by timkelty** [comment]
ah yep - I'm on Sierra 10.12.3 (16D32)

**Comment by pswai** [comment]
@timkelty Seems to be related to https://github.com/nodegit/nodegit/issues/1166. I'm trying out the suggestions there

**Comment by pswai** [comment]
~Installing `libgcrypt` via brew seems to resolve the issue. It's related with https://github.com/nodegit/nodegit/issues/1200~

No other issue came out. It's a bit late here, i'll have a look tomorrow.

**Comment by pswai** [comment]
OSX is not shipping true `openssl` since El Capitan, and with Sierra `libgcrypt` is not bundled as well. So far I have found 2 working workarounds (tested myself):

1. Install `libgcrypt` via brew (https://github.com/nodegit/nodegit/issues/801)
```
brew install libgcrypt
export C_INCLUDE_PATH=/usr/local/include
# the export is needed, otherwise `gcrypt.h` is not found
```

2. Install `openssl` and reinstall XCode CLT (https://github.com/nodegit/nodegit/issues/1124)
```
brew install openssl
sudo xcode-select --install
# i don't know why this works, still researching. If you find out why please let me know :)
```

Once nodegit binary is up for node 7.4.0, this issue will be gone (until node updates again)
